run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  fast: false
  enable:
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - exportloopref
    - govet
    - gosimple
    - gofmt
    - gofumpt
    - goconst
    - goimports
    - gomnd
    - gocyclo
    - ineffassign
    - lll
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unused
    - whitespace
    - wastedassign
    - unconvert
    - misspell

linters-settings:
  whitespace:
    multi-func: true
  lll:
    line-length: 160
  gomnd:
    # don't include the "operation", "argument" and "assign"
    checks:
      - case
      - condition
      - return
  goconst:
    ignore-tests: true
  gocyclo:
    # recommend 10-20
    min-complexity: 50
  misspell: # Finds commonly misspelled English words in comments
    locale: US